# Use root/example as user/password credentials
services:

  rabbitmq:
    image: rabbitmq:4.1-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=secret
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 10s
      timeout: 5s
      retries: 3

  mongo:
    image: mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - ./mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret

  clickhouse:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse-server
    ports:
      - "8124:8123"     # HTTP interface
      - "9001:9000"     # Native client port
      - "9010:9009"     # Replication/internal communication
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: secret
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: "1"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      # - ./config.xml:/etc/clickhouse-server/config.d/custom-config.xml
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8124/ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "19000:9000"       # API порт (S3)
      - "19001:9001"       # Порт веб-интерфейса
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address :9001
    restart: unless-stopped

volumes:
  rabbitmq_data:
  mongo_data:
  clickhouse_data:
  minio_data:
